AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vanityNumbersApp

  SAM template for vanity numbers app
  
Globals:
  Function:
    Timeout: 3

Resources:
  VanityNumbersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: vanity-numbers-app/built
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

Outputs:
  VanityNumbersFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt VanityNumbersFunction.Arn
  VanityNumbersFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt VanityNumbersFunctionRole.Arn
